Dataset:
  path: "./dataset/" # dataset path
  save: False # whether save or not
  show: True # whether show images or not

Scenario:
  type: 'merge1'
  NV_num : 5 # Neighbor Vehicle
  Jucntio_LiDAR_use : False # Junction LiDAR

  