Dataset:
  path: "./dataset/" # dataset path
  save: False # whether save or not
  show: True # whether show images or not

Scenario:
  type: 'merge1'
  weather_key: 0
  max_vehicles: 30
  junction_lidar : False # Junction LiDAR

NV:
  num_nv : 5 # Neighbor vehicle around EGO
  aggressive_car_percentage : 30 # 30 percent