Dataset:
  path: "./dataset/" # dataset path
  save: False # whether save or not
  show: True # whether show images or not

Scenario:
  type: 'merge1'
  num_nv : 5 # Neighbor vehicle around EGO
  weather_key: 0
  junction_lidar : False # Junction LiDAR

  